.PHONY:clean all
BIN=01test 02test
all:$(BIN)
01test.o:01test.c
	gcc -Wall -g -c $^ -o 01test.o
02test.o:02test.c
	gcc -Wall -g -c $^ -o 02test.o
01test:01test.o
	gcc -Wall -g $^ -o 01test
02test:02test.o
	gcc -Wall -g $^ -o 02test
clean:
	rm -f *.o $(BIN)
